drop table if exists ai_recognize_log;
drop table if exists ai_bind_token;
drop table if exists ai_call_log;
drop table if exists ai_provider;
drop table if exists trace_public_field;
drop table if exists harvest_record;
drop table if exists stock_out_order;
drop table if exists plant_operation_material;
drop table if exists plant_operation;
drop table if exists batch_status_log;
drop table if exists plant_batch;
drop table if exists stock_inventory;
drop table if exists farm_material;
drop table if exists farm_crop;
drop table if exists farm_plot;
drop table if exists sys_user;

create table sys_user (
    id bigint generated by default as identity primary key,
    username varchar(50) not null unique,
    password varchar(120) not null,
    display_name varchar(80) not null,
    role_code varchar(40) not null,
    data_scope varchar(40) not null,
    enabled int not null default 1
);

create table farm_plot (
    id bigint generated by default as identity primary key,
    name varchar(80) not null,
    area_mu decimal(12,2) not null,
    soil_type varchar(80),
    owner_id bigint,
    layout_x int not null,
    layout_y int not null,
    width int not null,
    height int not null,
    status varchar(40) not null
);

create table farm_crop (
    id bigint generated by default as identity primary key,
    name varchar(80) not null,
    variety varchar(80),
    min_growth_days int not null,
    image_url varchar(300)
);

create table farm_material (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    category varchar(40) not null,
    unit varchar(20) not null,
    safe_interval_days int not null default 0,
    enabled int not null default 1
);

create table stock_inventory (
    id bigint generated by default as identity primary key,
    material_id bigint not null,
    quantity decimal(14,2) not null,
    safety_stock decimal(14,2) not null,
    version int not null default 0
);

create table plant_batch (
    id bigint generated by default as identity primary key,
    batch_no varchar(80) not null unique,
    plot_id bigint not null,
    crop_id bigint not null,
    status varchar(40) not null,
    planned_area_mu decimal(12,2) not null,
    sow_date date,
    expected_harvest_date date,
    actual_harvest_date date,
    trace_code varchar(80),
    owner_id bigint,
    created_at timestamp not null default current_timestamp
);

create table batch_status_log (
    id bigint generated by default as identity primary key,
    batch_id bigint not null,
    from_status varchar(40),
    to_status varchar(40) not null,
    operator_name varchar(80) not null,
    reason varchar(300),
    created_at timestamp not null default current_timestamp
);

create table plant_operation (
    id bigint generated by default as identity primary key,
    batch_id bigint not null,
    type varchar(40) not null,
    operation_date date not null,
    worker_name varchar(80) not null,
    note varchar(500),
    is_locked int not null default 0,
    ref_operation_id bigint,
    created_at timestamp not null default current_timestamp
);

create table plant_operation_material (
    id bigint generated by default as identity primary key,
    operation_id bigint not null,
    material_id bigint not null,
    quantity decimal(14,2) not null
);

create table stock_out_order (
    id bigint generated by default as identity primary key,
    material_id bigint not null,
    quantity decimal(14,2) not null,
    type varchar(40) not null,
    operation_id bigint,
    created_at timestamp not null default current_timestamp
);

create table harvest_record (
    id bigint generated by default as identity primary key,
    batch_id bigint not null,
    harvest_date date not null,
    quantity_kg decimal(14,2) not null,
    quality_grade varchar(40) not null,
    trace_code varchar(80) not null,
    created_at timestamp not null default current_timestamp
);

create table trace_public_field (
    id bigint generated by default as identity primary key,
    field_key varchar(80) not null,
    public_enabled int not null
);

create table ai_provider (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    provider_type varchar(40) not null,
    base_url varchar(300) not null,
    api_key_mask varchar(80) not null,
    default_model varchar(120) not null,
    scene varchar(40) not null,
    priority int not null,
    enabled int not null
);

create table ai_call_log (
    id bigint generated by default as identity primary key,
    provider_id bigint,
    scene varchar(40) not null,
    prompt_summary varchar(500),
    success int not null,
    elapsed_ms int not null,
    created_at timestamp not null default current_timestamp
);

create table ai_bind_token (
    id bigint generated by default as identity primary key,
    token varchar(80) not null unique,
    pc_session_id varchar(120) not null,
    expires_at timestamp not null,
    used int not null default 0
);

create table ai_recognize_log (
    id bigint generated by default as identity primary key,
    image_hash varchar(120),
    crop_name varchar(80),
    result_json varchar(2000),
    created_at timestamp not null default current_timestamp
);
